# Generated by Django 5.1.7 on 2025-04-02 07:26

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aboutus", "0003_alter_restourant_orders_count"),
        ("main", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[("S", "s"), ("M", "m"), ("L", "l"), ("XL", "xl")],
                        default="M",
                        max_length=2,
                    ),
                ),
                (
                    "price_adjustment",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Narxni oshirish yoki kamaytirish uchun qiymat",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ovqat o'lchami",
                "verbose_name_plural": "1. Ovqat o'lchamlari",
            },
        ),
        migrations.CreateModel(
            name="Topping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Topping nomi")),
                (
                    "name_uz",
                    models.CharField(max_length=50, null=True, verbose_name="Topping nomi"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=50, null=True, verbose_name="Topping nomi"),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Topping narxi"),
                ),
            ],
            options={
                "verbose_name": "Qo'shimcha",
                "verbose_name_plural": "Qo'shimchalar",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "total_price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Umumiy narx"),
                ),
                (
                    "notes",
                    ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Kommentariya"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("confirmed", "Tasdiqlandi"),
                            ("delivered", "Yetkazildi"),
                            ("cancelled", "Bekor qilindi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holati",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("cash", "Naqd"), ("card", "Plastik")],
                        default="cash",
                        max_length=20,
                        verbose_name="To'lov usuli",
                    ),
                ),
                (
                    "restourant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aboutus.restourant",
                        verbose_name="orderrestourant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "Buyurtmalar",
            },
        ),
        migrations.CreateModel(
            name="OrderDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                ("quantity", models.IntegerField(verbose_name="Miqdori")),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi"),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.food",
                        verbose_name="Ovqatlar",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orderdetails",
                        to="services.order",
                        verbose_name="Buyurtmalar",
                    ),
                ),
                (
                    "size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.size",
                        verbose_name="O'lchami",
                    ),
                ),
                (
                    "topping",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.topping",
                        verbose_name="Qoshimchalar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtma tafsiloti",
                "verbose_name_plural": "Buyurtma tafsilotlari",
            },
        ),
    ]
