# Generated by Django 5.1.7 on 2025-04-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "verbose_name": "Buyurtma",
                "verbose_name_plural": "4.Buyurtmalar",
            },
        ),
        migrations.AlterModelOptions(
            name="orderdetails",
            options={
                "verbose_name": "Buyurtma tafsiloti",
                "verbose_name_plural": "3. Buyurtma tafsilotlari",
            },
        ),
        migrations.AlterModelOptions(
            name="topping",
            options={
                "verbose_name": "Qo'shimcha",
                "verbose_name_plural": "2. Qo'shimchalar",
            },
        ),
    ]
