# Generated by Django 5.1.7 on 2025-04-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercard",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=500, max_digits=12),
        ),
    ]
