# Generated by Django 5.1.7 on 2025-03-22 11:58

from typing import List, Tuple

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.common.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies: List[Tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_from_lang",
                    models.CharField(
                        blank=True,
                        choices=[("uz", "uzbekcha"), ("ru", "ruscha")],
                        max_length=60,
                        null=True,
                        verbose_name="slug tilini tanlash",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Shahar nomi")),
                (
                    "name_uz",
                    models.CharField(max_length=256, null=True, verbose_name="Shahar nomi"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=256, null=True, verbose_name="Shahar nomi"),
                ),
            ],
            options={
                "verbose_name": "Shahar",
                "verbose_name_plural": "1. Shaharlar",
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_from_lang",
                    models.CharField(
                        blank=True,
                        choices=[("uz", "uzbekcha"), ("ru", "ruscha")],
                        max_length=60,
                        null=True,
                        verbose_name="slug tilini tanlash",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Viloyat")),
                (
                    "name_uz",
                    models.CharField(max_length=256, null=True, verbose_name="Viloyat"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=256, null=True, verbose_name="Viloyat"),
                ),
                (
                    "phone_number",
                    apps.common.models.fields.PhoneField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="15 tadan son kam bolishi kerak...  Standart raqam talab qilinadi",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="Asosiy telefon raqam",
                    ),
                ),
                (
                    "detail_address",
                    models.CharField(max_length=256, verbose_name="Ko'cha nomi"),
                ),
                (
                    "detail_address_uz",
                    models.CharField(max_length=256, null=True, verbose_name="Ko'cha nomi"),
                ),
                (
                    "detail_address_ru",
                    models.CharField(max_length=256, null=True, verbose_name="Ko'cha nomi"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.city",
                        verbose_name="Shahar nomi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Manzil",
                "verbose_name_plural": "3. Manzillar",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_from_lang",
                    models.CharField(
                        blank=True,
                        choices=[("uz", "uzbekcha"), ("ru", "ruscha")],
                        max_length=60,
                        null=True,
                        verbose_name="slug tilini tanlash",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Tuman nomi")),
                (
                    "name_uz",
                    models.CharField(max_length=256, null=True, verbose_name="Tuman nomi"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=256, null=True, verbose_name="Tuman nomi"),
                ),
                (
                    "city",
                    models.ForeignKey(
                        max_length=256,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.city",
                        verbose_name="Shahar nomi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tuman nomi",
                "verbose_name_plural": "2. Tuman nomlari",
            },
        ),
    ]
