# Generated by Django 5.1.7 on 2025-03-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="address",
            name="slug_from_lang",
        ),
        migrations.RemoveField(
            model_name="city",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="city",
            name="slug_from_lang",
        ),
        migrations.RemoveField(
            model_name="district",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="district",
            name="slug_from_lang",
        ),
    ]
