# Generated by Django 5.1.7 on 2025-04-01 13:12

import apps.common.models.fields
import apps.common.utils
import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("aboutus", "0003_alter_restourant_orders_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryFood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_from_lang",
                    models.CharField(
                        blank=True,
                        choices=[("uz", "uzbekcha"), ("ru", "ruscha")],
                        max_length=60,
                        null=True,
                        verbose_name="slug tilini tanlash",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Kategoriyasi")),
                (
                    "name_uz",
                    models.CharField(max_length=256, null=True, verbose_name="Kategoriyasi"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=256, null=True, verbose_name="Kategoriyasi"),
                ),
                (
                    "image",
                    sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to="", verbose_name="Rasm"),
                ),
                (
                    "order",
                    apps.common.models.fields.OrderField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="tartib raqam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "1. Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Matn"),
                ),
                (
                    "name_uz",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Matn"),
                ),
                (
                    "name_ru",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Matn"),
                ),
                (
                    "discount_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Promo foizi",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Boshlanish sanasi"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="Tugash sanasi"),
                ),
            ],
            options={
                "verbose_name": "Promo Foiz",
                "verbose_name_plural": "4. Promo Foizlar",
            },
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                ("name", models.CharField(max_length=512, verbose_name="nomi")),
                (
                    "name_uz",
                    models.CharField(max_length=512, null=True, verbose_name="nomi"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=512, null=True, verbose_name="nomi"),
                ),
            ],
            options={
                "verbose_name": "Ovqatlar tegi",
                "verbose_name_plural": "3. Ovqatlar teglari",
            },
        ),
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_from_lang",
                    models.CharField(
                        blank=True,
                        choices=[("uz", "uzbekcha"), ("ru", "ruscha")],
                        max_length=60,
                        null=True,
                        verbose_name="slug tilini tanlash",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Ovqat nomi")),
                (
                    "name_uz",
                    models.CharField(max_length=255, null=True, verbose_name="Ovqat nomi"),
                ),
                (
                    "name_ru",
                    models.CharField(max_length=255, null=True, verbose_name="Ovqat nomi"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Ovqat tavsifi"),
                ),
                (
                    "description_uz",
                    models.TextField(blank=True, null=True, verbose_name="Ovqat tavsifi"),
                ),
                (
                    "description_ru",
                    models.TextField(blank=True, null=True, verbose_name="Ovqat tavsifi"),
                ),
                (
                    "base_price",
                    models.CharField(max_length=55, verbose_name="Asosiy narx"),
                ),
                ("is_promo_active", models.BooleanField(verbose_name="Faol Promo")),
                ("is_available", models.BooleanField(verbose_name="Ovqat mavjudligi")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food",
                        to="main.categoryfood",
                        verbose_name="Ovqat Kategorysi",
                    ),
                ),
                (
                    "restourant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aboutus.restourant",
                        verbose_name="restaurant_food",
                    ),
                ),
                (
                    "promo",
                    models.ManyToManyField(blank=True, to="main.promo", verbose_name="Promo"),
                ),
                (
                    "tags",
                    models.ManyToManyField(to="main.tags", verbose_name="Ovqat teglari"),
                ),
            ],
            options={
                "verbose_name": "Ovqat",
                "verbose_name_plural": "5. Ovqatlar",
            },
        ),
        migrations.CreateModel(
            name="FoodReviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Reyting",
                    ),
                ),
                (
                    "comment",
                    ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Komentariya"),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.food",
                        verbose_name="Ovqat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fikr-mulohaza",
                "verbose_name_plural": "6. Fikr-mulohazalar",
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "active",
                    apps.common.models.fields.ActiveField(default=False, verbose_name="active"),
                ),
                ("title", models.CharField(max_length=512, verbose_name="hujjat nomi")),
                (
                    "title_uz",
                    models.CharField(max_length=512, null=True, verbose_name="hujjat nomi"),
                ),
                (
                    "title_ru",
                    models.CharField(max_length=512, null=True, verbose_name="hujjat nomi"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.common.utils.generate_upload_path,
                        verbose_name="hujjat",
                    ),
                ),
                ("type", models.CharField(max_length=6)),
                (
                    "file_size",
                    models.FloatField(default=0, verbose_name="hujjat hajmi"),
                ),
                (
                    "order",
                    apps.common.models.fields.OrderField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="tartib raqam",
                    ),
                ),
                (
                    "food",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="main.food",
                        verbose_name="Ovqatlar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hujjar",
                "verbose_name_plural": "2. Hujjatlar",
                "ordering": ("order",),
            },
        ),
    ]
