# Generated by Django 5.1.7 on 2025-03-22 13:21

import ckeditor_uploader.fields
import django.core.validators
import django.db.models.deletion
import sorl.thumbnail.fields
from django.conf import settings
from django.db import migrations, models

import apps.common.models.fields
import apps.common.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryRestourant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_from_lang",
                    models.CharField(
                        blank=True,
                        choices=[("uz", "uzbekcha"), ("ru", "ruscha")],
                        max_length=60,
                        null=True,
                        verbose_name="slug tilini tanlash",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Kategoriyasi")),
                (
                    "order",
                    apps.common.models.fields.OrderField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="tartib raqam",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "3. Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="Restourant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "slug_from_lang",
                    models.CharField(
                        blank=True,
                        choices=[("uz", "uzbekcha"), ("ru", "ruscha")],
                        max_length=60,
                        null=True,
                        verbose_name="slug tilini tanlash",
                    ),
                ),
                (
                    "active",
                    apps.common.models.fields.ActiveField(default=False, verbose_name="active"),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Restourant nomi"),
                ),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "avatar",
                    sorl.thumbnail.fields.ImageField(
                        upload_to=apps.common.utils.generate_upload_path,
                        verbose_name="Rasm",
                    ),
                ),
                (
                    "cover_image",
                    sorl.thumbnail.fields.ImageField(
                        upload_to=apps.common.utils.generate_upload_path,
                        verbose_name="Asosiy rasm",
                    ),
                ),
                (
                    "location_url",
                    models.URLField(max_length=300, verbose_name="Joylashuvi"),
                ),
                (
                    "latitude",
                    models.CharField(blank=True, max_length=55, null=True, verbose_name="kenglik"),
                ),
                (
                    "longitude",
                    models.CharField(blank=True, max_length=55, null=True, verbose_name="uzunlik"),
                ),
                ("orders_count", models.IntegerField(verbose_name="Buyurtmalar soni")),
                (
                    "working_hourse",
                    models.CharField(
                        help_text="Masalan: 09:00 - 20:00",
                        max_length=50,
                        verbose_name="Ish vaqti",
                    ),
                ),
                (
                    "address_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.address",
                        verbose_name="Manzil",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="aboutus.categoryrestourant",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Restourant",
                "verbose_name_plural": "4. Restourantlar",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="FavouriteRestaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favourite",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
                (
                    "restourant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favouriteuser",
                        to="aboutus.restourant",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sevimli restoran",
                "verbose_name_plural": "2. Sevimli restoranlar",
            },
        ),
        migrations.CreateModel(
            name="Reviews",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Kiritilgan sana"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="O'zgartrilgan sana"),
                ),
                (
                    "rating",
                    models.FloatField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(1.0),
                            django.core.validators.MaxValueValidator(5.0),
                        ],
                        verbose_name="Reyting",
                    ),
                ),
                (
                    "comment",
                    ckeditor_uploader.fields.RichTextUploadingField(verbose_name="Komentariya"),
                ),
                (
                    "restourant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restourant",
                        to="aboutus.restourant",
                        verbose_name="Restoran",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fikr-mulohaza",
                "verbose_name_plural": "1. Fikr-mulohazalar",
            },
        ),
    ]
