# Generated by Django 5.1.7 on 2025-03-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoryrestourant",
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "4. Kategoriyalar",
            },
        ),
        migrations.AlterModelOptions(
            name="favouriterestaurant",
            options={
                "verbose_name": "Sevimli restoran",
                "verbose_name_plural": "3. Sevimli restoranlar",
            },
        ),
        migrations.AlterModelOptions(
            name="restourant",
            options={
                "ordering": ("id",),
                "verbose_name": "Restourant",
                "verbose_name_plural": "1. Restourantlar",
            },
        ),
        migrations.AlterModelOptions(
            name="reviews",
            options={
                "verbose_name": "Fikr-mulohaza",
                "verbose_name_plural": "2. Fikr-mulohazalar",
            },
        ),
        migrations.AddField(
            model_name="categoryrestourant",
            name="name_ru",
            field=models.CharField(max_length=256, null=True, verbose_name="Kategoriyasi"),
        ),
        migrations.AddField(
            model_name="categoryrestourant",
            name="name_uz",
            field=models.CharField(max_length=256, null=True, verbose_name="Kategoriyasi"),
        ),
        migrations.AddField(
            model_name="restourant",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AddField(
            model_name="restourant",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AddField(
            model_name="restourant",
            name="name_ru",
            field=models.CharField(max_length=255, null=True, verbose_name="Restourant nomi"),
        ),
        migrations.AddField(
            model_name="restourant",
            name="name_uz",
            field=models.CharField(max_length=255, null=True, verbose_name="Restourant nomi"),
        ),
    ]
