# Generated by Django 5.1.7 on 2025-03-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0002_alter_categoryrestourant_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restourant",
            name="orders_count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Buyurtmalar soni"),
        ),
    ]
