# Generated by Django 5.1.7 on 2025-04-22 12:48

import apps.common.utils
import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0003_alter_restourant_orders_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restourant",
            name="avatar",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to=apps.common.utils.generate_upload_path,
                verbose_name="Rasm",
            ),
        ),
        migrations.AlterField(
            model_name="restourant",
            name="cover_image",
            field=sorl.thumbnail.fields.ImageField(
                blank=True,
                null=True,
                upload_to=apps.common.utils.generate_upload_path,
                verbose_name="Asosiy rasm",
            ),
        ),
    ]
