# Generated by Django 5.1.7 on 2025-04-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "Xabar", "verbose_name_plural": "2. Xabarlar"},
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "verbose_name": "Xona nomi",
                "verbose_name_plural": "1. Xona nomlari",
            },
        ),
    ]
